---
services:
  postgres:
    image: postgres:16-bookworm
    container_name: actual_gym_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      postgres
      -c log_statement=mod
      -c log_min_error_statement=error
      -c log_line_prefix='%m [%p] %u@%d (%r) '
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

  back-end:
    container_name: actual_gym_backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  db_data:
